/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-summary.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-if.d.ts" />
/// <reference path="../raml-aware/raml-aware.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../markdown-styles/markdown-styles.d.ts" />
/// <reference path="../marked-element/marked-element.d.ts" />
/// <reference path="../iron-meta/iron-meta.d.ts" />

declare namespace ApiElements {

  /**
   * `api-summary`
   *
   * A summary view for an API base on AMF data model
   *
   * ## Styling
   *
   * `<api-summary>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--api-summary` | Mixin applied to this elment | `{}`
   * `--api-summary-url-font-size` | Font size of endpoin URL | `16px`
   * `--api-summary-url-background-color` | Background color of the URL section | `#424242`
   * `--api-summary-url-font-color` | Font color of the URL area | `#fff`
   */
  class ApiSummary extends Polymer.Element {

    /**
     * `raml-aware` scope property to use.
     */
    aware: string|null|undefined;

    /**
     * Generated AMF json/ld model form the API spec.
     * The element assumes the object of the first array item to be a
     * type of `"http://raml.org/vocabularies/document#Document`
     * on AMF vocabulary.
     *
     * It is only usefult for the element to resolve references.
     */
    amfModel: object|any[]|null;

    /**
     * Computed value of AMF model of a type of `http://schema.org/WebAPI`
     */
    readonly webApi: object|null;

    /**
     * A property to set to override AMF's model base URI information.
     * When this property is set, the `endpointUri` property is recalculated.
     */
    baseUri: string|null|undefined;

    /**
     * API base URI to display in main URL field.
     * This value is computed when `amfModel` or `baseUri` change.
     */
    readonly apiBaseUri: string|null|undefined;

    /**
     * Computed title of the API
     */
    readonly apiTitle: string|null|undefined;

    /**
     * Computed value of method description from `method` property.
     */
    readonly description: string|null|undefined;

    /**
     * Computed value of the `http://raml.org/vocabularies/http#server`
     * from `amfModel`
     */
    readonly server: object|null|undefined;

    /**
     * Computed API version label
     */
    readonly version: string|null|undefined;
    readonly hasVersion: boolean|null|undefined;
    readonly protocols: string|null|undefined;
    readonly hasProtocols: boolean|null|undefined;

    /**
     * Checks if property item has a type.
     *
     * @param model Model item.
     * @param type A type to lookup
     */
    _hasType(model: object|null, type: String|null): Boolean|null;

    /**
     * Gets a signle scalar value from a model.
     *
     * @param model Amf model to extract the value from.
     * @param key Model key to search for the value
     * @returns Value for key
     */
    _getValue(model: object|null, key: String|null): any|null;

    /**
     * Computes AMF's `http://schema.org/WebAPI` model
     *
     * @param amf AMF json/ld model for an API
     * @returns Web API declaration.
     */
    _computeWebApi(amf: any[]|object|null): object|null;

    /**
     * Computes value of `description` property.
     *
     * @param shape Shape of AMF model.
     * @returns Description if defined.
     */
    _computeDescription(shape: object|null): String|null|undefined;

    /**
     * Computes value of `apiTitle` property.
     *
     * @param shape Shape of AMF model.
     * @returns Description if defined.
     */
    _computeApiTitle(shape: object|null): String|null|undefined;

    /**
     * Computes value for `server` property that is later used with other computations.
     *
     * @param webApi Cusrent value of `webApi`
     * @returns The server model
     */
    _computeServer(webApi: object|null): object|null;
    _computeVersion(webApi: any): any;
    _computeHasVersion(version: any): any;
    _computeProtocols(webApi: any): any;
    _computeHasProtocols(protocols: any): any;

    /**
     * Computes API's URI based on `amfModel` and `baseUri` property.
     *
     * @param server Server model of AMF API.
     * @param baseUri Current value of `baseUri` property
     * @returns Endpoint's URI
     */
    _computeBaseUri(server: object|null, baseUri: String|null): String|null;

    /**
     * Computes base URI value from either `baseUri`, `iron-meta` with
     * `ApiBaseUri` key or `amfModel` value (in this order).
     *
     * @param baseUri Value of `baseUri` property
     * @param server AMF API model for Server.
     * @returns Base uri value. Can be empty string.
     */
    _getBaseUri(baseUri: String|null, server: object|null): String|null;

    /**
     * Computes base URI from AMF model.
     *
     * @param server AMF API model for Server.
     * @returns Base uri value if exists.
     */
    _getAmfBaseUri(server: object|null): String|null|undefined;

    /**
     * Displays array values.
     */
    _displayArray(arr: any): any;
  }
}

interface HTMLElementTagNameMap {
  "api-summary": ApiElements.ApiSummary;
}
